version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "5051:8080"
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
